version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  chat-app:
    build: ./
    depends_on:
      - db
    ports:
      - 3000:3000
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:secret@db:5432/postgres
      - NEXTAUTH_URL=http://20.244.44.28:3000
      - NEXTAUTH_SECRET=secret
      - WEBSOCKET_URL=ws://20.244.44.28:8080

volumes:
  pgdata: