name: Deploying App

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "**"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.4
              with:
                ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
            
            - name: Add Known Hosts
              run: |
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_KNOWN_HOSTS}}" > ~/.ssh/known_hosts
            
            - name: Deploy to azure vm
              env:
                NEXTAUTH_URL: ${{secrets.NEXAUTH_URL}}
                NEXTAUTH_SECRET: ${{secrets.NEXAUTH_SECRET}}
                WEBSOCKET_URL: ${{secrets.WEBSOCKET_URL}}
              run: |
                ssh -o StrictHostKeyChecking=yes mayank@20.244.44.28 << 'EOF'
                    cd ~/chatapp/chat-app-2.0
                    git pull origin main
                    sudo docker-compose down
                    sudo docker-compose up -d --build
                EOF