name: Deploying App

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "**"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.4
              with:
                ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
            
            - name: Add Known Hosts
              run: |
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_KNOWN_HOSTS}}" > ~/.ssh/known_hosts
            
            - name: Deploy to azure vm
              env:
                DATABASE_URL: ${{secrets.DATABASE_URL}}
                NEXTAUTH_URL: ${{secrets.NEXAUTH_URL}}
                NEXTAUTH_SECRET: ${{secrets.NEXAUTH_SECRET}}
                WEBSOCKET_URL: ${{secrets.WEBSOCKET_URL}}
              run: |
                echo "DATABASE_URL=${{secrets.DATABASE_URL}}" > .env
                echo "NEXTAUTH_URL=${{secrets.NEXAUTH_URL}}" >> .env
                echo "NEXTAUTH_SECRET=${{secrets.NEXAUTH_SECRET}}" >> .env
                echo "WEBSOCKET_URL=${{secrets.WEBSOCKET_URL}}" >> .env
                scp -o StrictHostKeyChecking=no .env ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }}:~/chat-app/chat-app-2.0/.env
                ssh -o StrictHostKeyChecking=yes ${{secrets.VM_USERNAME}}@${{secrets.VM_IP}} << 'EOF'
                    cd ~/chatapp/chat-app-2.0
                    git pull origin main
                    sudo docker-compose down
                    sudo docker-compose up -d --build
                EOF