name: Deploying App

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "**"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up SSH
              uses: web
              with:
                ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
            
            - name: Add Known Hosts
              run: |
                mkdir -p ~/.ssh
                echo "${{secrets.KNOWN_HOSTS}}" > ~/.ssh/known_hosts
            
            - name: Deploy to azure vm
              run: |
                ssh mayank@20.244.6.69 << 'EOF'
                    cd /chatapp
                    git pull origin main
                    docker-compose down
                    docker-compose up -d --build
                EOF